(autoload 'auto-compile-modify-hooks            "auto-compile" "" nil)
(autoload 'auto-compile-mode                    "auto-compile" "" t)
(autoload 'toggle-local-auto-compile            "auto-compile" "" t)
(autoload 'auto-compile-kill-local              "auto-compile" "" t)
(autoload 'auto-compile-file-do                 "auto-compile" "" nil)
(autoload 'auto-compile-file-ask                "auto-compile" "" nil)
(autoload 'auto-compile-file-maybe              "auto-compile" "" nil)
(autoload 'auto-compile-file-match-1            "auto-compile" "" nil)
(autoload 'auto-compile-file-match              "auto-compile" "" nil)
(provide 'auto-compile-epkg-autoloads)
